#!/bin/sh
LAN=eth0
INET=eth1
VPN=tun0

# Удаление всех правил в таблице "filter" (по-умолчанию).
iptables -F

# Удаление правил в таблице "nat" (её надо указать явно).
iptables -F -t nat

# По-умолчанию все маршрутизируемые пакеты выбрасываются.
iptables --policy FORWARD DROP

# ICMP разрешим
iptables -A FORWARD -p icmp -j ACCEPT

# Разрешаем любую маршрутизацию для интерфейса VPN
iptables -A FORWARD -i \$VPN -j ACCEPT
iptables -A FORWARD -o \$VPN -j ACCEPT

# DNAT для 80 порта и 25
iptables -t nat -A PREROUTING -p tcp --dport 80 -i \$INET -j DNAT --to 10.10.4.10:80
iptables -t nat -A PREROUTING -p tcp --dport 25 -i \$INET -j DNAT --to 10.10.4.20:25

# TCP разрешаем
iptables -A FORWARD -i \$INET -o \$LAN -p tcp -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -i \$INET -o \$LAN -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i \$LAN -o \$INET -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT
